config/routes.rb
Books::Application.routes.draw do
  resources :books

  root :to => "home#index"

  devise_for :users

  resources :users, :only => :show do
    resources :bookmarks
  end

  match "search" => "books#search", :as => :search
  match "results" => "books#results", :as => :results

  match "books/:id/add" => "books#add"

end

app/models/author.rb
class Author < ActiveRecord::Base
  belongs_to :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :bookmarks
  has_many :users, :through => :bookmarks
  has_many :authors
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable 
  devise :database_authenticatable, :registerable, :recoverable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  has_many :bookmarks
  has_many :books, :through => :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @bookmarks = @user.bookmarks

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end

  def show
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookmark }
    end
  end

  def new
    @bookmark = Bookmark.new

    respond_to do |format|
      format.html
      format.json { redner json: @bookmark }
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @bookmark = Bookmark.new(params[:bookmark])
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render json: @bookmark, status: :created, location: @bookmark }
      else
        format.html { render action: "new" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :ok }
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :ok }
    end
  end

  def search
  end

  def results
    if(params[:q])
      @results = GoogleBooks::API.search(params[:q], :ip_address => request.env['HTTP_X_FORWARDED_FOR'])
      @book = Book.new
    end
  end

  def add
    @bookmark = Bookmark.new
    @bookmark.book_id = params[:id]
    @bookmark.user_id = current_user.id
    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to "/users/" + current_user.id.to_s + "/bookmarks/" + @bookmark.id.to_s, notice: 'Bookmark was successfully created.' }
        format.json { render json: @bookmark, status: :created, location: @bookmark }
      else
        format.html { render action: "show" , controller: "books"}
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    if @user
      @books = @user.books
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  module ApplicationHelper
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def ip() 
    request.env['HTTP_X_FORWARDED_FOR'] || request.remote_ip 
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
	<% @bookmark.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :book_id %><br />
	<%= f.text_field :book_id %>
  </div>
  <div class="field">
    <%= f.label :shelf %><br />
    <%= select_tag(:shelf)%>
    <%= options_for_select([['To Read', "To Read"], ['Reading', "Reading"], ['Read', "Read"]], 3) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>
<% render 'form' %>

<%= link_to 'Show', user_bookmark_path %> |
<%= link_to 'Back', user_bookmarks_path %>

app/views/bookmarks/index.html.erb
<h1>Bookmarks</h1>

<table>
  <tr>
    <th>Book ID</th>
    <th>User ID</th>
    <th>Shelf</th>
    <th></th>
  </tr>

<% @bookmarks.each do |bookmark| %>
  <tr>
    <td><%= bookmark.book_id %></td>
    <td><%= bookmark.user_id %></td>
    <td><%= bookmark.shelf %></td>
  </tr>
<% end %>
</table>

<br />

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Book ID:</b>
  <%= @bookmark.book_id %>
</p>

<p>
  <b>User ID:</b>
  <%= @bookmark.user_id %>
</p>

<p>
  <b>Shelf:</b>
  <%= @bookmark.shelf %>
</p>
<%= link_to 'Edit', edit_user_bookmark_path %> |
<%= link_to 'Back', user_bookmarks_path %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
	<% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :published_date %><br />
    <%= f.text_field :published_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :isbn_10 %><br />
    <%= f.text_field :isbn_10 %>
  </div>
  <div class="field">
    <%= f.label :page_count %><br />
    <%= f.text_field :page_count %>
  </div>
  <div class="field">
    <%= f.label :average_rating %><br />
    <%= f.text_field :average_rating %>
  </div>
  <div class="field">
    <%= f.label :ratings_count %><br />
    <%= f.text_field :ratings_count %>
  </div>
  <div class="field">
    <%= f.label :preview_link %><br />
    <%= f.text_field :preview_link %>
  </div>
  <div class="field">
    <%= f.label :info_link %><br />
    <%= f.text_field :info_link %>
  </div>
  <div class="field">
    <%= f.label :cover_thumbnail %><br />
    <%= f.text_field :cover_thumbnail %>
  </div>
  <div class="field">
    <%= f.label :cover_small %><br />
    <%= f.text_field :cover_small %>
  </div>
  <div class="field">
    <%= f.label :cover_medium %><br />
    <%= f.text_field :cover_medium %>
  </div>
  <div class="field">
    <%= f.label :cover_large %><br />
    <%= f.text_field :cover_large %>
  </div>
  <div class="field">
    <%= f.label :cover_extra_large %><br />
    <%= f.text_field :cover_extra_large %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/add.html.erb
<p id="notice"><%= notice %></p>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
  <tr>
    <th></th>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= image_tag(book.cover_thumbnail) %></td>
    <td><%= book.title %></td>
    <td>
      <%= @description = book.description %>
      <%= raw @description %>
    </td>
    <td><%= link_to 'Show', book %></td>
    <td>
      <% @user = current_user %>
      <%= form_tag("/books/" + book.id.to_s  + "/add", :method => "post") do %>
	<%= hidden_field(:book, :value => book.id) %>
	<%= submit_tag("Add") %>
      <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/results.html.erb
<%= link_to("Back to Search", search_path) %>
Hello: <%= request.env['HTTP_X_FORWARDED_FOR'] %>
<table>
  <% for book in @results %>
    <tr>
      <td>
	<% if book.covers[:thumbnail] %>
	  <%= image_tag(book.covers[:thumbnail]) %>
	<% end %>
      </td>
      <td><%= book.title %></td>
      <td>
	<% book.authors.each do |author|  %>
	  <%= author %><br/>
	<% end  %>
      </td>
      <td>
	<% if book.description %>
	  <%= raw (@description = book.description) %>
	<% end %>
      </td>
      <td>
	<%= form_for @book do |f| %>
	  <%= f.hidden_field(:title, :value => book.title) %>
	  <%= f.hidden_field(:publisher, :value => book.publisher) %>
	  <%= f.hidden_field(:published_date, :value => book.published_date) %>
	  <%= f.hidden_field(:description, :value => book.description) %>
	  <%= f.hidden_field(:isbn, :value => book.isbn) %>
	  <%= f.hidden_field(:isbn_10, :value => book.isbn_10) %>
	  <%= f.hidden_field(:page_count, :value => book.page_count) %>
	  <%= f.hidden_field(:average_rating, :value => book.average_rating) %>
	  <%= f.hidden_field(:ratings_count, :value => book.ratings_count) %>
	  <%= f.hidden_field(:preview_link, :value => book.preview_link) %>
	  <%= f.hidden_field(:info_link, :value => book.info_link) %>
	  <%= f.hidden_field(:cover_thumbnail, :value => book.covers[:thumbnail]) %>
	  <%= f.hidden_field(:cover_small, :value => book.covers[:small]) %>
	  <%= f.hidden_field(:cover_medium, :value => book.covers[:medium]) %>
	  <%= f.hidden_field(:cover_large, :value => book.covers[:large]) %>
	  <%= f.hidden_field(:cover_extra_large, :value => book.covers[:extra_large]) %>

	  <div class="actions">
	    <%= f.submit %>
	  </div>
	<% end %>
      </td>
    </tr>

  <% end %>
</table>

app/views/books/search.html.erb
<%= form_tag(results_path, :method => "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/books/show.html.erb
<h2>
  <%= @book.title %>
</h2>

<p id="notice"><%= notice %></p>

<div class="span-12">
  <%= image_tag(@book.cover_medium, :width => "400") %>
</div>

<div class="span-12">
<p>
  <b>Publisher:</b>
  <%= @book.publisher %>
</p>

<p>
  <b>Published date:</b>
  <%= @book.published_date %>
</p>

<p>
  <b>Description:</b>
  <%= @book.description %>
</p>

<p>
  <b>Isbn:</b>
  <%= @book.isbn %>
</p>

<p>
  <b>Isbn 10:</b>
  <%= @book.isbn_10 %>
</p>

<p>
  <b>Page count:</b>
  <%= @book.page_count %>
</p>

<p>
  <b>Average rating:</b>
  <%= @book.average_rating %>
</p>

<p>
  <b>Ratings count:</b>
  <%= @book.ratings_count %>
</p>

<p>
  <%= link_to("Preview link", @book.preview_link) %>
</p>

<p>
  <%= link_to("Info link", @book.info_link) %>
</p>
</div>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
  <% if user_signed_in? %>
    <%= render 'shared/shelves' %>
  <% else %>
    <div class="span-8">
    <h3>To Read</h3>
  <p>Slaughterhouse-Five by:Kurt Vonnegut</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor <sub>sub text</sub> ut labore et <sup>sup text</sup> magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

<div class="span-8">
  <h3>Reading</h3>
  <p class="small">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
  <p class="large">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</div>

<div class="span-8 last">
  <h3>Read</h3>
  <div class="box">
    <p class="last">Aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
  <blockquote>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </blockquote>
<% end %>

</div>

<!-- <h3>Home</h3> -->
<!-- <% @users.each do |user| %> -->
  <!--   <p>User: <%=link_to user.name, user %></p> -->
  <!-- <% end %> -->

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dewie</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= params[:controller] %>">
    <div id="container" class="container">
      <header>
	<h1>
	  <%= link_to('Books', root_url) %>
	</h1>
        <nav>
          <ul class="hmenu">
            <%= render 'shared/navigation' %>
          </ul>
        </nav>
	<hr />
        <%- flash.each do |name, msg| -%>
          <%= content_tag :div, msg, :id => "flash_\#{name}" if msg.is_a?(String) %>
        <%- end -%>
      </header>
      <div id="main" role="main">
	<%= yield %>
      </div>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/shared/_navigation.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to('Bookmarks', user_bookmarks_path(current_user)) %>
  </li>
  <li>
    <%= link_to('Books', books_url) %>
  </li>
  <li>
    <%= link_to('Search', search_url) %>
  </li>
  <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
  </li>
  <li>
    <%= link_to('Edit account', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
    <%= link_to('Login', new_user_session_path)  %>  
  </li>
  <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
  </li>
<% end %>

app/views/shared/_shelves.html.erb
<div class="span-8">
  <h3>To Read</h3>
  <table>
<% @books.each do |book| %>
  <tr>
    <td><%= image_tag(book.cover_thumbnail) %></td>
    <td><h4><%= link_to book.title, book %><h4></td>
  </tr>
<% end %>
</table>
</div>
<div class="span-8">
  <h3>Reading</h3>
</div>
<div class="span-8">
  <h3>Read<h3>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>